import Link from "next/link";

export const metadata = {
  title: "Terms of Service - IPH Photobooth",
  description: "Terms of Service for IPH Photobooth software by Intania Production House.",
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-950 text-gray-300">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <Link
          href="/"
          className="inline-flex items-center text-sm text-gray-400 hover:text-white transition-colors mb-12"
        >
          &larr; Back to Home
        </Link>

        <h1 className="text-4xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-gray-500 mb-12">Last updated: February 28, 2026</p>

        <div className="space-y-10 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By downloading, installing, or using the IPH Photobooth application
              (&quot;Software&quot;), you agree to be bound by these Terms of Service
              (&quot;Terms&quot;). If you do not agree to these Terms, do not use the Software.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. License</h2>
            <p>
              Intania Production House (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) grants
              you a limited, non-exclusive, non-transferable, revocable license to use the Software
              for personal or organizational event purposes, subject to these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. Permitted Use</h2>
            <p>You may use the Software to:</p>
            <ul className="list-disc list-inside mt-3 space-y-1 text-gray-400">
              <li>Capture and process photos at events</li>
              <li>Create collages and photo layouts</li>
              <li>Print or share photos generated by the Software</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Restrictions</h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside mt-3 space-y-1 text-gray-400">
              <li>Reverse engineer, decompile, or disassemble the Software</li>
              <li>Modify, adapt, or create derivative works based on the Software</li>
              <li>Distribute, sublicense, lease, or lend the Software to third parties</li>
              <li>Remove or alter any proprietary notices or labels on the Software</li>
              <li>Use the Software for any unlawful purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Intellectual Property</h2>
            <p>
              The Software and all associated intellectual property rights remain the exclusive
              property of Intania Production House. These Terms do not grant you any rights to our
              trademarks, logos, or brand assets.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Content Ownership</h2>
            <p>
              All photos, collages, and media you create using the Software belong entirely to you.
              We claim no ownership or rights over any content you produce with the Software.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Disclaimer of Warranties</h2>
            <p>
              The Software is provided &quot;as is&quot; and &quot;as available&quot; without
              warranties of any kind, either express or implied, including but not limited to
              implied warranties of merchantability, fitness for a particular purpose, and
              non-infringement. We do not warrant that the Software will be uninterrupted,
              error-free, or free of harmful components.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by applicable law, Intania Production House shall not
              be liable for any indirect, incidental, special, consequential, or punitive damages,
              or any loss of profits, data, or goodwill, arising out of or in connection with your
              use of the Software.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Termination</h2>
            <p>
              We reserve the right to terminate or suspend your access to the Software at any time,
              without prior notice, for conduct that we believe violates these Terms or is harmful
              to other users or our interests. Upon termination, your license to use the Software
              will immediately cease.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">10. Changes to These Terms</h2>
            <p>
              We may revise these Terms at any time by updating this page. Your continued use of the
              Software after changes are posted constitutes your acceptance of the revised Terms. We
              encourage you to review this page periodically.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">11. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at{" "}
              <a
                href="mailto:hammymukura@gmail.com"
                className="text-blue-400 hover:text-blue-300 underline transition-colors"
              >
                hammymukura@gmail.com
              </a>
              .
            </p>
          </section>
        </div>

        <div className="border-t border-gray-800 mt-16 pt-8 text-center text-sm text-gray-500">
          <p>&copy; {new Date().getFullYear()} Intania Production House. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
}
